// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuApLM9BK7YCdxzZDVNbYTsD6lh15BS98',
    appId: '1:986310523307:web:e220922f23b8ec0ccbfaee',
    messagingSenderId: '986310523307',
    projectId: 'ecommerce-3a44a',
    authDomain: 'ecommerce-3a44a.firebaseapp.com',
    storageBucket: 'ecommerce-3a44a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4AGO06irTXD-1I-0AUlkEzCRcvsFTxkY',
    appId: '1:986310523307:android:9b5845e14848e4b0cbfaee',
    messagingSenderId: '986310523307',
    projectId: 'ecommerce-3a44a',
    storageBucket: 'ecommerce-3a44a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKVk6hgiVxxADyqwR8x5_dsW1nq0ToZeg',
    appId: '1:986310523307:ios:4e1af1cc4bfb0377cbfaee',
    messagingSenderId: '986310523307',
    projectId: 'ecommerce-3a44a',
    storageBucket: 'ecommerce-3a44a.firebasestorage.app',
    iosBundleId: 'com.example.xpiriaApp',
  );
}
