import 'dart:async';
import 'dart:developer' as developer;

import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:dio/dio.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_messaging/firebase_messaging.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/widgets.dart';
import 'package:flutter_local_notifications/flutter_local_notifications.dart';
import 'package:go_router/go_router.dart';
import 'package:xpiria_app/firebase_options.dart';

/// Handles Firebase push notifications and notifications generated by the app.
class NotificationService {
  NotificationService._();

  static final NotificationService instance = NotificationService._();

  static const _channel = AndroidNotificationChannel(
    'ecommerce_notifications',
    'Ecommerce notifications',
    description: 'Offers, orders and important ecommerce updates.',
    importance: Importance.high,
  );

  final FirebaseMessaging _messaging = FirebaseMessaging.instance;
  final FirebaseAuth _auth = FirebaseAuth.instance;
  final FirebaseFirestore _firestore = FirebaseFirestore.instance;
  final FlutterLocalNotificationsPlugin _localNotifications =
      FlutterLocalNotificationsPlugin();
  GoRouter? _router;
  String? _pendingRoute;

  void _log(String message) {
    developer.log(message, name: 'NotificationService');
    debugPrint('[NotificationService] $message');
  }

  Future<void> initialize() async {
    _log('Initializing notifications.');
    await _messaging.setAutoInitEnabled(true);
    await _initializeLocalNotifications();
    await _requestPermission();

    // iOS displays remote notifications itself when the application is open.
    await _messaging.setForegroundNotificationPresentationOptions(
      alert: true,
      badge: true,
      sound: true,
    );

    FirebaseMessaging.onMessage.listen(_showForegroundPush);
    FirebaseMessaging.onMessageOpenedApp.listen(_handleNotificationTap);

    final initialMessage = await _messaging.getInitialMessage();
    if (initialMessage != null) {
      _handleNotificationTap(initialMessage);
    }

    _auth.authStateChanges().listen((user) {
      _log('Authentication changed. uid=${user?.uid ?? 'none'}');
      unawaited(_registerTokenForUser(user));
    });
    _messaging.onTokenRefresh.listen(_saveToken);
    await _registerTokenForUser(_auth.currentUser);
  }

  void attachRouter(GoRouter router) {
    _router = router;
    final pendingRoute = _pendingRoute;
    if (pendingRoute != null && _auth.currentUser != null) {
      _pendingRoute = null;
      WidgetsBinding.instance.addPostFrameCallback((_) {
        if (_router == router && _auth.currentUser != null) {
          _log('Opening pending notification route: $pendingRoute');
          router.go(pendingRoute);
        }
      });
    }
  }

  Future<void> _initializeLocalNotifications() async {
    // flutter_local_notifications targets native platforms, not browsers.
    if (kIsWeb) return;

    const settings = InitializationSettings(
      android: AndroidInitializationSettings('@mipmap/ic_launcher'),
      iOS: DarwinInitializationSettings(),
    );

    await _localNotifications.initialize(
      settings,
      onDidReceiveNotificationResponse: (response) {
        _openRoute(response.payload);
      },
    );

    if (!kIsWeb && defaultTargetPlatform == TargetPlatform.android) {
      await _localNotifications
          .resolvePlatformSpecificImplementation<
            AndroidFlutterLocalNotificationsPlugin
          >()
          ?.createNotificationChannel(_channel);
    }
  }

  Future<void> _requestPermission() async {
    final settings = await _messaging.requestPermission(
      alert: true,
      badge: true,
      sound: true,
      provisional: false,
    );
    _log('Notification permission: ${settings.authorizationStatus.name}');

    if (!kIsWeb && defaultTargetPlatform == TargetPlatform.android) {
      await _localNotifications
          .resolvePlatformSpecificImplementation<
            AndroidFlutterLocalNotificationsPlugin
          >()
          ?.requestNotificationsPermission();
    }
  }

  Future<void> _showForegroundPush(RemoteMessage message) async {
    // Apple already presents foreground push notifications through APNs.
    if (!kIsWeb && defaultTargetPlatform == TargetPlatform.iOS) return;

    final notification = message.notification;
    await showLocalNotification(
      title:
          notification?.title ?? message.data['title'] as String? ?? 'Xpiria',
      body:
          notification?.body ??
          message.data['body'] as String? ??
          'Tienes una nueva actualizacion.',
      payload: message.data['route'] as String?,
    );
  }

  Future<void> showLocalNotification({
    required String title,
    required String body,
    String? payload,
  }) async {
    if (kIsWeb) return;

    const details = NotificationDetails(
      android: AndroidNotificationDetails(
        'ecommerce_notifications',
        'Ecommerce notifications',
        channelDescription: 'Offers, orders and important ecommerce updates.',
        importance: Importance.high,
        priority: Priority.high,
        icon: '@mipmap/ic_launcher',
      ),
      iOS: DarwinNotificationDetails(
        presentAlert: true,
        presentBadge: true,
        presentSound: true,
      ),
    );

    await _localNotifications.show(
      DateTime.now().millisecondsSinceEpoch.remainder(100000),
      title,
      body,
      details,
      payload: payload,
    );
  }

  Future<void> sendPurchaseNotification({
    required String transactionId,
    required double amount,
    required String currency,
  }) async {
    if (!kDebugMode) return;

    try {
      final token = await _messaging.getToken();
      if (token == null || token.isEmpty) {
        _log('Purchase notification skipped because the FCM token is missing.');
        return;
      }

      const configuredHost = String.fromEnvironment('LOCAL_FUNCTIONS_HOST');
      final host = configuredHost.isNotEmpty
          ? configuredHost
          : (!kIsWeb && defaultTargetPlatform == TargetPlatform.android
                ? '10.0.2.2'
                : '127.0.0.1');
      final endpoint =
          'http://$host:5001/ecommerce-3a44a/us-central1/'
          'purchase_notification';

      await Dio().post<void>(
        endpoint,
        data: {
          'token': token,
          'transactionId': transactionId,
          'amount': amount,
          'currency': currency,
        },
        options: Options(contentType: Headers.jsonContentType),
      );
      _log('Purchase notification requested for $transactionId.');
    } catch (error, stackTrace) {
      _log('Purchase saved, but its local notification could not be sent.');
      developer.log(
        'Could not request the local purchase notification.',
        name: 'NotificationService',
        error: error,
        stackTrace: stackTrace,
      );
    }
  }

  void _handleNotificationTap(RemoteMessage message) {
    final transactionId =
        message.data['transactionId'] ?? message.data['saleId'];
    final route = message.data['route'] as String?;
    _openRoute(
      route ??
          (transactionId == null ? null : '/transaction-detail/$transactionId'),
    );
  }

  Future<void> _registerTokenForUser(User? user) async {
    if (user == null) {
      _log(
        'Token registration skipped because there is no authenticated user.',
      );
      return;
    }

    _log('Requesting FCM token for user ${user.uid}.');

    String? token;
    for (var attempt = 1; attempt <= 3 && token == null; attempt++) {
      try {
        token = await _messaging.getToken();
      } on FirebaseException catch (error, stackTrace) {
        final message =
            'Could not get the FCM token '
            '(attempt $attempt/3, code=${error.code}, '
            'plugin=${error.plugin}, message=${error.message ?? 'none'}).';
        _log(message);
        developer.log(
          message,
          name: 'NotificationService',
          error: error,
          stackTrace: stackTrace,
        );
      } catch (error, stackTrace) {
        _log('Unexpected error getting the FCM token (attempt $attempt/3).');
        developer.log(
          'Unexpected error getting the FCM token (attempt $attempt/3).',
          name: 'NotificationService',
          error: error,
          stackTrace: stackTrace,
        );
      }

      if (token == null && attempt < 3) {
        await Future<void>.delayed(Duration(seconds: attempt * 2));
      }
    }

    if (token == null) {
      _log('The FCM token is still unavailable after 3 attempts.');
    } else {
      _log('FCM returned a token; saving it in Firestore.');
      if (kDebugMode) debugPrint('[NotificationService] FCM token: $token');
      await _saveToken(token);
    }

    final pendingRoute = _pendingRoute;
    if (pendingRoute != null) _openRoute(pendingRoute);
  }

  Future<void> _saveToken(String token) async {
    final user = _auth.currentUser;
    if (user == null) return;

    try {
      await _firestore.collection('user_devices').doc(user.uid).set({
        'fcmTokens': FieldValue.arrayUnion([token]),
        'updatedAt': FieldValue.serverTimestamp(),
      }, SetOptions(merge: true));
      _log('FCM token registered for user ${user.uid}.');
    } on FirebaseException catch (error, stackTrace) {
      final message =
          'Could not save the FCM token in Firestore '
          '(code=${error.code}, message=${error.message ?? 'none'}).';
      _log(message);
      developer.log(
        message,
        name: 'NotificationService',
        error: error,
        stackTrace: stackTrace,
      );
    }
  }

  void _openRoute(String? route) {
    if (route == null || !route.startsWith('/transaction-detail/')) {
      _log('Notification route ignored: ${route ?? 'none'}');
      return;
    }
    if (_auth.currentUser == null || _router == null) {
      _log('Notification route queued until authentication is ready: $route');
      _pendingRoute = route;
      return;
    }

    _pendingRoute = null;
    _log('Opening notification route: $route');
    _router!.go(route);
  }
}

@pragma('vm:entry-point')
Future<void> firebaseMessagingBackgroundHandler(RemoteMessage message) async {
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  developer.log(
    'Push received in background: ${message.messageId}',
    name: 'NotificationService',
  );
}
