import 'dart:developer' as developer;

import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_messaging/firebase_messaging.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter_local_notifications/flutter_local_notifications.dart';
import 'package:xpiria_app/firebase_options.dart';

/// Handles Firebase push notifications and notifications generated by the app.
class NotificationService {
  NotificationService._();

  static final NotificationService instance = NotificationService._();

  static const _channel = AndroidNotificationChannel(
    'ecommerce_notifications',
    'Ecommerce notifications',
    description: 'Offers, orders and important ecommerce updates.',
    importance: Importance.high,
  );

  final FirebaseMessaging _messaging = FirebaseMessaging.instance;
  final FlutterLocalNotificationsPlugin _localNotifications =
      FlutterLocalNotificationsPlugin();

  Future<void> initialize() async {
    await _initializeLocalNotifications();
    await _requestPermission();

    // iOS displays remote notifications itself when the application is open.
    await _messaging.setForegroundNotificationPresentationOptions(
      alert: true,
      badge: true,
      sound: true,
    );

    FirebaseMessaging.onMessage.listen(_showForegroundPush);
    FirebaseMessaging.onMessageOpenedApp.listen(_handleNotificationTap);

    final initialMessage = await _messaging.getInitialMessage();
    if (initialMessage != null) {
      _handleNotificationTap(initialMessage);
    }

    try {
      final token = await _messaging.getToken();
      developer.log('FCM token: $token', name: 'NotificationService');
    } on FirebaseException catch (error) {
      developer.log(
        'The FCM token is not available yet: ${error.message}',
        name: 'NotificationService',
      );
    }
    _messaging.onTokenRefresh.listen(
      (newToken) => developer.log(
        'FCM token refreshed: $newToken',
        name: 'NotificationService',
      ),
    );
  }

  Future<void> _initializeLocalNotifications() async {
    // flutter_local_notifications targets native platforms, not browsers.
    if (kIsWeb) return;

    const settings = InitializationSettings(
      android: AndroidInitializationSettings('@mipmap/ic_launcher'),
      iOS: DarwinInitializationSettings(),
    );

    await _localNotifications.initialize(
      settings,
      onDidReceiveNotificationResponse: (response) {
        developer.log(
          'Local notification opened. Payload: ${response.payload}',
          name: 'NotificationService',
        );
      },
    );

    if (!kIsWeb && defaultTargetPlatform == TargetPlatform.android) {
      await _localNotifications
          .resolvePlatformSpecificImplementation<
            AndroidFlutterLocalNotificationsPlugin
          >()
          ?.createNotificationChannel(_channel);
    }
  }

  Future<void> _requestPermission() async {
    await _messaging.requestPermission(
      alert: true,
      badge: true,
      sound: true,
      provisional: false,
    );

    if (!kIsWeb && defaultTargetPlatform == TargetPlatform.android) {
      await _localNotifications
          .resolvePlatformSpecificImplementation<
            AndroidFlutterLocalNotificationsPlugin
          >()
          ?.requestNotificationsPermission();
    }
  }

  Future<void> _showForegroundPush(RemoteMessage message) async {
    // Apple already presents foreground push notifications through APNs.
    if (!kIsWeb && defaultTargetPlatform == TargetPlatform.iOS) return;

    final notification = message.notification;
    await showLocalNotification(
      title: notification?.title ?? message.data['title'] as String? ?? 'Xpiria',
      body:
          notification?.body ??
          message.data['body'] as String? ??
          'Tienes una nueva actualizacion.',
      payload: message.data['route'] as String?,
    );
  }

  Future<void> showLocalNotification({
    required String title,
    required String body,
    String? payload,
  }) async {
    if (kIsWeb) return;

    const details = NotificationDetails(
      android: AndroidNotificationDetails(
        'ecommerce_notifications',
        'Ecommerce notifications',
        channelDescription: 'Offers, orders and important ecommerce updates.',
        importance: Importance.high,
        priority: Priority.high,
        icon: '@mipmap/ic_launcher',
      ),
      iOS: DarwinNotificationDetails(
        presentAlert: true,
        presentBadge: true,
        presentSound: true,
      ),
    );

    await _localNotifications.show(
      DateTime.now().millisecondsSinceEpoch.remainder(100000),
      title,
      body,
      details,
      payload: payload,
    );
  }

  void _handleNotificationTap(RemoteMessage message) {
    developer.log(
      'Push notification opened. Data: ${message.data}',
      name: 'NotificationService',
    );
  }
}

@pragma('vm:entry-point')
Future<void> firebaseMessagingBackgroundHandler(RemoteMessage message) async {
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  developer.log(
    'Push received in background: ${message.messageId}',
    name: 'NotificationService',
  );
}
